name: aegis
description: "A privacy-focused on-device scam detection app."

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.0.0
  html: ^0.15.0
  tflite_flutter: ^0.12.1
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.0
  share_plus: ^7.2.0
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^9.2.4
  local_auth: ^3.0.2
  crypto: ^3.0.6
  flutter_embedder: 0.1.7
  flutter_onnxruntime: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

dependency_overrides:
  flutter_rust_bridge: 2.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/ml/aegis/
    - assets/ml/scamshield_model.tflite
    - assets/ml/word_index.json
    - assets/ml/scam_model.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#0B1020"
    theme_color: "#7C3AED"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true
